name: covid_data
channels:
  - defaults
dependencies:
  - backcall=0.2.0
  - ca-certificates=2020.10.14
  - certifi=2020.11.8
  - colorama=0.4.4
  - decorator=4.4.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - libsodium=1.0.18
  - openssl=1.1.1h
  - pickleshare=0.7.5
  - prompt-toolkit=3.0.8
  - python=3.8.5
  - python-dateutil=2.8.1
  - setuptools=50.3.2
  - six=1.15.0
  - sqlite=3.33.0
  - tornado=6.1
  - traitlets=5.0.5
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - wheel=0.36.0
  - wincertstore=0.2
  - zeromq=4.3.3
  - zlib=1.2.11
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - bleach==3.2.1
    - cffi==1.14.4
    - chardet==3.0.4
    - cycler==0.10.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - idna==2.10
    - jinja2==2.11.2
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyterlab==2.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==1.2.0
    - kiwisolver==1.3.1
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.5
    - numpy==1.19.4
    - packaging==20.7
    - pandas==1.1.4
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pillow==8.0.1
    - pip==20.3.1
    - prometheus-client==0.9.0
    - pycparser==2.20
    - pygments==2.7.3
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytz==2020.4
    - pywin32==300
    - pywinpty==0.5.7
    - pyzmq==20.0.0
    - requests==2.25.0
    - scipy==1.5.4
    - seaborn==0.11.0
    - send2trash==1.5.0
    - terminado==0.9.1
    - testpath==0.4.4
    - urllib3==1.26.2
    - webencodings==0.5.1
