name: covid_data
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.10.14
  - certifi=2020.11.8
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1h
  - python=3.8.5
  - readline=8.0
  - setuptools=50.3.2
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - cffi==1.14.4
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - idna==2.10
    - ipykernel==5.3.4
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==2.11.2
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.7.0
    - jupyterlab==2.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==1.2.0
    - kiwisolver==1.3.1
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - notebook==6.1.5
    - numpy==1.19.4
    - packaging==20.7
    - pandas==1.1.4
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.1
    - pip==20.3.1
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.8
    - ptyprocess==0.6.0
    - pycparser==2.20
    - pygments==2.7.3
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pyzmq==20.0.0
    - requests==2.25.0
    - scipy==1.5.4
    - seaborn==0.11.0
    - send2trash==1.5.0
    - six==1.15.0
    - terminado==0.9.1
    - testpath==0.4.4
    - tornado==6.1
    - traitlets==5.0.5
    - urllib3==1.26.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
